use std::{env, error::Error, fs, path::Path};

use serde::Deserialize;

fn main() -> Result<(), Box<dyn Error>> {
    embuild::espidf::sysenv::output();
    generate_pins_config()?;
    generate_ble_config()?;
    Ok(())
}

#[derive(Debug, Deserialize)]
struct PinConfig {
    led: u8,
    button: u8,
}

#[derive(Debug, Deserialize)]
struct BleConfig {
    service_uuid: String,
    characteristic_uuid: String,
    device_name: String,
}

fn generate_pins_config() -> Result<(), Box<dyn Error>> {
    // デフォルト値（従来のハードコードと同じ）
    let default = PinConfig {
        led: 12,
        button: 14,
    };

    let config_path = Path::new("config/pins.json");
    let cfg: PinConfig = match fs::read_to_string(config_path) {
        Ok(data) => serde_json::from_str(&data)?,
        Err(e) => {
            eprintln!(
                "Warning: failed to read pin configuration from {}: {}. Falling back to defaults (led={}, button={}).",
                config_path.display(),
                e,
                default.led,
                default.button,
            );
            default
        }
    };

    // サポートするピンを制限し、安全に型を生成
    fn pin_type(num: u8) -> Result<&'static str, Box<dyn Error>> {
        match num {
            2 => Ok("esp_idf_hal::gpio::Gpio2"),
            4 => Ok("esp_idf_hal::gpio::Gpio4"),
            5 => Ok("esp_idf_hal::gpio::Gpio5"),
            12 => Ok("esp_idf_hal::gpio::Gpio12"),
            13 => Ok("esp_idf_hal::gpio::Gpio13"),
            14 => Ok("esp_idf_hal::gpio::Gpio14"),
            15 => Ok("esp_idf_hal::gpio::Gpio15"),
            _ => Err(format!("unsupported pin number: {num}").into()),
        }
    }

    if cfg.led == cfg.button {
        return Err(format!("led and button pins must differ: {}", cfg.led).into());
    }

    let led_ty = pin_type(cfg.led)?;
    let button_ty = pin_type(cfg.button)?;

    let code = format!(
        "// Auto-generated by build.rs. Do not edit manually.\n\n\
         pub type LedPinType = {led};\n\
         pub type ButtonPinType = {button};\n\
         pub fn split_pins(peripherals: esp_idf_hal::peripherals::Peripherals) -> (LedPinType, ButtonPinType) {{\n\
             let pins = peripherals.pins;\n\
             (pins.{led_field}, pins.{button_field})\n\
         }}\n",
        led = led_ty,
        button = button_ty,
        led_field = format!("gpio{}", cfg.led),
        button_field = format!("gpio{}", cfg.button),
    );

    let out_dir = env::var("OUT_DIR")?;
    fs::write(Path::new(&out_dir).join("pins_gen.rs"), code)?;

    // コンフィグが変わったらリビルド
    println!("cargo:rerun-if-changed=config/pins.json");
    Ok(())
}

fn generate_ble_config() -> Result<(), Box<dyn Error>> {
    let default = BleConfig {
        service_uuid: "9b574847-f706-436c-bed7-fc01eb0965c1".to_string(),
        characteristic_uuid: "681285a6-247f-48c6-80ad-68c3dce18585".to_string(),
        device_name: "esp32-devkit-v1".to_string(),
    };

    let config_path = Path::new("config/ble.json");
    let cfg: BleConfig = match fs::read_to_string(config_path) {
        Ok(data) => serde_json::from_str(&data)?,
        Err(e) => {
            eprintln!(
                "Warning: failed to read BLE configuration from {}: {}. Falling back to defaults (service_uuid={}, characteristic_uuid={}, device_name={}).",
                config_path.display(),
                e,
                &default.service_uuid,
                &default.characteristic_uuid,
                &default.device_name,
            );
            default
        }
    };

    fn escape_rust_string(value: &str) -> String {
        value.chars().flat_map(|c| c.escape_default()).collect()
    }

    let service_uuid_escaped = escape_rust_string(&cfg.service_uuid);
    let characteristic_uuid_escaped = escape_rust_string(&cfg.characteristic_uuid);
    let device_name_escaped = escape_rust_string(&cfg.device_name);

    let code = format!(
        "// Auto-generated by build.rs. Do not edit manually.\n\n\
         pub const BLE_SERVICE_UUID: &str = \"{service_uuid}\";\n\
         pub const BLE_CHARACTERISTIC_UUID: &str = \"{characteristic_uuid}\";\n\
         pub const BLE_DEVICE_NAME: &str = \"{device_name}\";\n",
        service_uuid = service_uuid_escaped,
        characteristic_uuid = characteristic_uuid_escaped,
        device_name = device_name_escaped,
    );

    let out_dir = env::var("OUT_DIR")?;
    fs::write(Path::new(&out_dir).join("ble_gen.rs"), code)?;

    println!("cargo:rerun-if-changed=config/ble.json");
    Ok(())
}
